version: '3'

services:
  app:
    image: ruslandobrov/spring-library-app:1.0
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: spring_library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d